# Generated by Django 5.0 on 2025-03-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_wplan_content_wcontent_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
