# Generated by Django 5.0 on 2025-03-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_plan_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
