# Generated by Django 5.0 on 2025-04-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_enrollment_membershipplan_remove_client_last_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='SelectMembershipplan',
        ),
    ]
