# Generated by Django 5.0 on 2025-04-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_enrollment_selectmembershipplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='enroll',
        ),
    ]
