# Generated by Django 5.0 on 2025-04-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_enrollment_enroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='first_name',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='client_usrname',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='last_name',
        ),
        migrations.AddField(
            model_name='enroll',
            name='Gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
