# Generated by Django 5.0 on 2025-04-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_email_enroll_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='user',
            new_name='client_usrname',
        ),
    ]
