# Generated by Django 5.2.7 on 2025-11-04 23:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_enroll_is_active_enroll_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-datetime']},
        ),
        migrations.AddField(
            model_name='discussion',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
        migrations.AddField(
            model_name='discussion',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_solution', models.BooleanField(default=False)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.discussion')),
                ('replied_by_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_replies', to='main.client')),
                ('replied_by_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_replies', to='main.trainer')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
