# Generated by Django 4.2.30 on 2026-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_discussion_upvoted_by_discussion_viewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
