# Generated by Django 4.2.30 on 2026-08-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_discussion_upvoted_by_discussion_viewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_usrname',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='client_usrname',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_usrname',
            field=models.CharField(default='head', max_length=50, unique=True),
        ),
    ]
